version: '3.8'

services:
  redis-exporter:
    image: "aws-exporter-app:VERSION"
    command: python3 app.py redis
    restart: always
    network_mode: host
    depends_on:
      - redis
    volumes:
      - ./conf/metrics:/app/conf/metrics
      - ./conf/configs.yaml:/app/conf/configs.yaml
    environment:
      TZ: Asia/Shanghai
  rds-exporter:
    image: "aws-exporter-app:VERSION"
    command: python3 app.py rds
    restart: always
    network_mode: host
    depends_on:
      - redis
    volumes:
      - ./conf/metrics:/app/conf/metrics
      - ./conf/configs.yaml:/app/conf/configs.yaml
    environment:
      TZ: Asia/Shanghai

  redis:
    image: "redis:6.2"
    hostname: redis
    restart: always
    network_mode: host
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
