{
 "title": "AWS RDS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(aws_rds_cpu_utilization_average, account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_rds_cpu_utilization_average{account=~\"$account\"}, region)"
    }
   },
   {
    "name": "projname",
    "label": "projname",
    "query": {
     "query": "label_values(aws_rds_cpu_utilization_average{account=~\"$account\", region=~\"$region\"}, projname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(aws_rds_cpu_utilization_average{account=~\"$account\", region=~\"$region\", projname=~\"$projname\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "实例详情【账号维度】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_rds_cpu_utilization_average{account=~\"$account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_rds_database_connections_average{account=~\"$account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_rds_disk_allocated_storage{account=~\"$account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_rds_freeable_memory_average{account=~\"$account\"}/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(aws_rds_disk_allocated_storage{account=~\"$account\"} - aws_rds_free_storage_space_average{account=~\"$account\"} / 1024 / 1024 /1024) / aws_rds_disk_allocated_storage{account=~\"$account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "aws_rds_cpu_utilization_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(aws_rds_disk_allocated_storage{instance=~\"$instance\"} - aws_rds_free_storage_space_average{instance=~\"$instance\"} / 1024 / 1024 /1024) / aws_rds_disk_allocated_storage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "可用内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS操作所花费的平均时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "aws_rds_read_latency_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 读IOPS"
    },
    {
     "expr": "aws_rds_write_latency_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 写IOPS"
    }
   ]
  },
  {
   "title": "IOPS操作数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "aws_rds_read_i_o_p_s_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 读IOPS"
    },
    {
     "expr": "aws_rds_write_i_o_p_s_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 写IOPS"
    }
   ]
  },
  {
   "title": "网络吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "aws_rds_network_receive_throughput_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 网络接收吞吐量"
    },
    {
     "expr": "aws_rds_network_transmit_throughput_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 网络传输吞吐量"
    }
   ]
  },
  {
   "title": "磁盘吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 读取吞吐量"
    },
    {
     "expr": "aws_rds_write_throughput_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 写入吞吐量"
    }
   ]
  },
  {
   "title": "等待访问磁盘的未完成 I/O（读/写请求）数 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "aws_rds_disk_queue_depth_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "交换空间使用情况 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "aws_rds_swap_usage_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "复制延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "aws_rds_replica_lag_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}