{
 "title": "AWS Redis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(aws_redis_cpu_utilization_average, account)"
    }
   },
   {
    "name": "region",
    "label": "accountregion",
    "query": {
     "query": "label_values(aws_redis_cpu_utilization_average{account=~\"$account\"}, region)"
    }
   },
   {
    "name": "projname",
    "label": "projname",
    "query": {
     "query": "label_values(aws_redis_cpu_utilization_average{account=~\"$account\", region=~\"$region\"}, projname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(aws_redis_cpu_utilization_average{account=~\"$account\", region=~\"$region\", projname=~\"$projname\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "是否在执行bgsave",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_redis_save_in_progress_average{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "是否master节点",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_redis_is_master_average{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "从节点延迟",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_redis_replication_lag_average{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "可用内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_redis_freeable_memory_average{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "引擎分配内存的效率",
   "type": "stat",
   "description": "表示Redis引擎分配内存的效率。某些阈值表示不同的行为。推荐值是让碎片高于 1.0。这是从 Redis INFOmem_fragmentation_ratio statistic的计算出来的",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_redis_memory_fragmentation_ratio_average{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实例总览【账号维度】",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "aws_redis_cpu_utilization_average{account=~\"$account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_redis_curr_connections_average{account=~\"$account\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_redis_database_memory_usage_percentage_average{account=~\"$account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "实例详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aws_redis_cpu_utilization_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "aws_redis_database_memory_usage_percentage_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "aws_redis_curr_connections_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 当前"
    },
    {
     "expr": "aws_redis_new_connections_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 新建"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "aws_redis_cache_hit_rate_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "网络吞吐量 - 包数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "aws_redis_network_packets_in_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 接收"
    },
    {
     "expr": "aws_redis_network_packets_out_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 发送"
    }
   ]
  },
  {
   "title": "网络吞吐量 - 流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "aws_redis_network_bytes_in_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 接收"
    },
    {
     "expr": "aws_redis_network_bytes_out_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 发送"
    }
   ]
  },
  {
   "title": "Redis 为所有目的分配的字节总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "aws_redis_bytes_used_for_cache_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB0平均 TTL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "aws_redis_d_b__average_t_t_l_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "活动碎片整理进程每分钟执行的值重新分配次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "aws_redis_active_defrag_hits_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Redis 为所有目的分配的字节总数",
   "type": "timeseries",
   "description": "Redis 为所有目的（包括数据集、缓冲区等）分配的字节的总数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "aws_redis_bytes_used_for_cache_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "key统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "key数量统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "aws_redis_curr_items_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 缓存中的key数"
    },
    {
     "expr": "aws_redis_curr_volatile_items_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 设置了 ttl 的key数"
    }
   ]
  },
  {
   "title": "被驱逐key数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "aws_redis_evictions_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 缓存中的key数"
    }
   ]
  },
  {
   "title": "过期key总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "aws_redis_reclaimed_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "只读键查找次数(成功/不成功)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "aws_redis_cache_hits_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 成功"
    },
    {
     "expr": "aws_redis_cache_misses_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - 不成功"
    }
   ]
  },
  { "title": "集群", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "复制组写入负载",
   "type": "timeseries",
   "description": "对于重复配置中的节点，ReplicationBytes 报告主项向其所有副本发送的字节数。此指标代表复制组上的写入负载。这是根据 Redis INFO 中的 master_repl_offset 统计数据得出的。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "aws_redis_replication_bytes_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "从节点延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "aws_redis_replication_lag_average{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "数据分层的集群指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "从磁盘读取的字节总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "aws_redis_bytes_read_from_disk_average{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "写入磁盘的总字节数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "aws_redis_bytes_written_to_disk_average{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}